#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Lets the Chrome Web Store workflow (.github/workflows/chrome-web-store.yml) submit
# releases without a stored key:
#
#   scripts/setup-chrome-web-store.sh
#
# It creates a Google Cloud service account (no key) and a Workload Identity Federation
# provider that trusts only that workflow on dev, links the account in the Chrome Web
# Store dashboard, and sets four GitHub repository variables. None of them is a secret.
# Values are remembered in .env.chrome-web-store (git-ignored) for re-runs. Every step
# checks what already exists, so re-running is safe.

cd "$(dirname "$0")/.."
export GH_REPO="zhangchi0104/open-browser-translate"
ENV_FILE=".env.chrome-web-store"
DEVCONSOLE="https://chrome.google.com/webstore/devconsole"
WORKFLOW_FILE=".github/workflows/chrome-web-store.yml"
DEFAULT_BRANCH="dev"
SA_NAME="chrome-web-store-ci"
POOL_ID="github"
PROVIDER_ID="open-browser-translate"

# run CMD… shows a command, runs it, and on failure offers a retry.
run() {
  while :; do
    printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"
    if "$@"; then return 0; fi
    warn "That command failed."
    confirm "Retry?" || { say "Fix it and run this wizard again."; exit 1; }
  done
}

TOTAL_STAGES=10

banner "Chrome Web Store release setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check prerequisites"
ok=true
if ! command -v gcloud >/dev/null 2>&1; then
  warn "The Google Cloud CLI is not installed: https://cloud.google.com/sdk/docs/install"; ok=false
elif [[ -z "$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null)" ]]; then
  warn "gcloud is not signed in. Run: gcloud auth login"; ok=false
fi
if ! command -v gh >/dev/null 2>&1; then
  warn "The GitHub CLI is not installed: https://cli.github.com"; ok=false
elif ! gh auth status >/dev/null 2>&1; then
  warn "gh is not signed in. Run: gh auth login"; ok=false
else
  permission=$(gh repo view "$GH_REPO" --json viewerPermission -q .viewerPermission 2>/dev/null || true)
  if [[ "$permission" != "ADMIN" ]]; then
    warn "The active gh account can't manage $GH_REPO's variables (permission: ${permission:-none})."
    note "Switch to the owner: gh auth switch --user zhangchi0104"
    ok=false
  fi
fi
if [[ "$ok" != true ]]; then
  printf '\n'; say "Fix the above, then run this wizard again."; exit 1
fi
REPO_ID=$(gh api "repos/$GH_REPO" -q .id)
say "${GREEN}✓${RESET} gcloud ($(gcloud auth list --filter=status:ACTIVE --format='value(account)' | head -n1)) and gh (admin on $GH_REPO) are ready."
printf '\n'
say "The Chrome Web Store API can't create a new item, so the first version must"
say "already be uploaded by hand (docs/chrome-web-store-listing.md, sections 0–5)."
confirm "Does the extension already have an item in the developer dashboard?" || {
  say "Create the item first, then run this wizard again."; exit 1; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Chrome Web Store: publisher ID"
open_url "$DEVCONSOLE"
step "Sign in with the account that owns the extension, and pick its publisher if asked."
step "The address bar now reads $DEVCONSOLE/<publisher-id>/…"
step "Copy the <publisher-id> part (between /devconsole/ and the next /)."
ask CHROME_PUBLISHER_ID "Publisher ID:"
while [[ -z "$CHROME_PUBLISHER_ID" || "$CHROME_PUBLISHER_ID" == */* ]]; do
  warn "Paste only the ID segment, without slashes."
  ask CHROME_PUBLISHER_ID "Publisher ID:"
done
write_env CHROME_PUBLISHER_ID "$CHROME_PUBLISHER_ID"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Chrome Web Store: extension ID"
open_url "$DEVCONSOLE/$CHROME_PUBLISHER_ID"
step "In the Items list, click Open Browser Translate."
step "Copy the 32-letter item ID shown under its name (also in the address bar)."
ask CHROME_EXTENSION_ID "Extension ID:"
while [[ ! "$CHROME_EXTENSION_ID" =~ ^[a-p]{32}$ ]]; do
  warn "An extension ID is 32 letters from a to p."
  ask CHROME_EXTENSION_ID "Extension ID:"
done
write_env CHROME_EXTENSION_ID "$CHROME_EXTENSION_ID"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: project"
say "The service account and the identity provider live in a Google Cloud project."
say "Use an existing one or create one (e.g. open-browser-translate)."
open_url "https://console.cloud.google.com/projectcreate"
note "No billing account is needed. Copy the project ID, not its name or number."
ask GCP_PROJECT_ID "Project ID:"
until gcloud projects describe "$GCP_PROJECT_ID" >/dev/null 2>&1; do
  warn "gcloud can't see a project '$GCP_PROJECT_ID' with your account."
  ask GCP_PROJECT_ID "Project ID:"
done
GCP_PROJECT_NUMBER=$(gcloud projects describe "$GCP_PROJECT_ID" --format='value(projectNumber)')
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
say "${GREEN}✓${RESET} Project $GCP_PROJECT_ID (number $GCP_PROJECT_NUMBER)"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: enable APIs"
say "The Chrome Web Store API, plus the three APIs GitHub OIDC sign-in goes through."
printf '\n'
run gcloud services enable --project="$GCP_PROJECT_ID" \
  chromewebstore.googleapis.com iam.googleapis.com iamcredentials.googleapis.com sts.googleapis.com
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: service account"
GCP_SERVICE_ACCOUNT="$SA_NAME@$GCP_PROJECT_ID.iam.gserviceaccount.com"
if gcloud iam service-accounts describe "$GCP_SERVICE_ACCOUNT" --project="$GCP_PROJECT_ID" >/dev/null 2>&1; then
  say "${GREEN}✓${RESET} $GCP_SERVICE_ACCOUNT already exists."
else
  say "Creating $GCP_SERVICE_ACCOUNT. It gets no project roles and no key."
  printf '\n'
  run gcloud iam service-accounts create "$SA_NAME" --project="$GCP_PROJECT_ID" \
    --display-name="Chrome Web Store CI" \
    --description="Submits releases of $GH_REPO; signed in to through GitHub OIDC"
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: trust GitHub Actions"
WORKFLOW_REF="$GH_REPO/$WORKFLOW_FILE@refs/heads/$DEFAULT_BRANCH"
CONDITION="assertion.repository_id == '$REPO_ID' && assertion.workflow_ref == '$WORKFLOW_REF'"
POOL="projects/$GCP_PROJECT_NUMBER/locations/global/workloadIdentityPools/$POOL_ID"
GCP_WORKLOAD_IDENTITY_PROVIDER="$POOL/providers/$PROVIDER_ID"
say "A Workload Identity Federation provider that accepts GitHub's OIDC tokens only from"
note "  $WORKFLOW_REF"
note "  (repository ID $REPO_ID, so a renamed or re-created repo can't use it)"
say "and lets them act as $GCP_SERVICE_ACCOUNT."
printf '\n'
if ! gcloud iam workload-identity-pools describe "$POOL_ID" --project="$GCP_PROJECT_ID" --location=global >/dev/null 2>&1; then
  run gcloud iam workload-identity-pools create "$POOL_ID" --project="$GCP_PROJECT_ID" \
    --location=global --display-name="GitHub Actions"
fi
provider_args=(--project="$GCP_PROJECT_ID" --location=global --workload-identity-pool="$POOL_ID"
  --display-name="$PROVIDER_ID"
  --attribute-mapping="google.subject=assertion.sub,attribute.repository_id=assertion.repository_id,attribute.workflow_ref=assertion.workflow_ref"
  --attribute-condition="$CONDITION")
if gcloud iam workload-identity-pools providers describe "$PROVIDER_ID" --project="$GCP_PROJECT_ID" \
  --location=global --workload-identity-pool="$POOL_ID" >/dev/null 2>&1; then
  run gcloud iam workload-identity-pools providers update-oidc "$PROVIDER_ID" "${provider_args[@]}"
else
  run gcloud iam workload-identity-pools providers create-oidc "$PROVIDER_ID" "${provider_args[@]}" \
    --issuer-uri="https://token.actions.githubusercontent.com"
fi
run gcloud iam service-accounts add-iam-policy-binding "$GCP_SERVICE_ACCOUNT" --project="$GCP_PROJECT_ID" \
  --role=roles/iam.workloadIdentityUser \
  --member="principalSet://iam.googleapis.com/$POOL/attribute.repository_id/$REPO_ID" \
  --condition=None --format=none
say "${GREEN}✓${RESET} Provider: $GCP_WORKLOAD_IDENTITY_PROVIDER"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Chrome Web Store: link the service account"
open_url "$DEVCONSOLE/$CHROME_PUBLISHER_ID"
step "In the left sidebar, open Account."
step "Find the service account setting and add this email, then save:"
printf '\n      %s%s%s\n\n' "$BOLD" "$GCP_SERVICE_ACCOUNT" "$RESET"
note "A publisher can have only one service account; replace any old one."
pause "Press Enter once it's saved."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "GitHub: set the repository variables"
say "These go to $GH_REPO → Settings → Secrets and variables → Actions → Variables."
say "None is a secret: without the OIDC token only that workflow gets, they grant nothing."
note "  CHROME_EXTENSION_ID              $CHROME_EXTENSION_ID"
note "  CHROME_PUBLISHER_ID              $CHROME_PUBLISHER_ID"
note "  GCP_WORKLOAD_IDENTITY_PROVIDER   $GCP_WORKLOAD_IDENTITY_PROVIDER"
note "  GCP_SERVICE_ACCOUNT              $GCP_SERVICE_ACCOUNT"
printf '\n'
warn "From the next feat/fix release on main, CI submits every release for review."
if confirm "Set them now (overwrites existing values)?"; then
  set_var CHROME_EXTENSION_ID "$CHROME_EXTENSION_ID"
  set_var CHROME_PUBLISHER_ID "$CHROME_PUBLISHER_ID"
  set_var GCP_WORKLOAD_IDENTITY_PROVIDER "$GCP_WORKLOAD_IDENTITY_PROVIDER"
  set_var GCP_SERVICE_ACCOUNT "$GCP_SERVICE_ACCOUNT"
else
  SKIPPED+=("GitHub variables (re-run this wizard to set them)")
fi
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Check it end to end"
say "OIDC only works inside GitHub Actions, so the check is a dry run of the workflow:"
say "it signs in as $SA_NAME and reads the item's status, uploading nothing."
printf '\n'
LATEST_TAG=$(gh release list --exclude-pre-releases --limit 1 --json tagName -q '.[0].tagName' 2>/dev/null || true)
if ! gh workflow view chrome-web-store.yml >/dev/null 2>&1; then
  warn "The Chrome Web Store workflow isn't on $DEFAULT_BRANCH yet."
  SKIPPED+=("Once it is: Actions → Chrome Web Store → Run workflow, tag ${LATEST_TAG:-<latest>}, dry_run ticked")
elif [[ -z "$LATEST_TAG" ]]; then
  warn "No stable release to check against yet."
  SKIPPED+=("After the first stable release: Actions → Chrome Web Store → Run workflow with dry_run")
elif confirm "Run a dry run against $LATEST_TAG now?"; then
  run gh workflow run chrome-web-store.yml --ref "$DEFAULT_BRANCH" -f tag="$LATEST_TAG" -f dry_run=true
  say "Waiting for the run to start…"
  sleep 5
  run_id=$(gh run list --workflow chrome-web-store.yml --event workflow_dispatch --limit 1 --json databaseId -q '.[0].databaseId')
  if gh run watch "$run_id" --exit-status; then
    say "${GREEN}✓${RESET} The workflow signed in and can reach the item."
  else
    warn "The dry run failed. Its log says which step:"
    note "  Sign in to Google Cloud: the provider condition, or the APIs (stages 5 and 7)"
    note "  Submit, HTTP 401/403: the service account isn't linked yet (stage 8), or it was"
    note "    just linked; wait a minute and re-run the job"
    note "  Submit, HTTP 404: the publisher or extension ID is wrong (stages 2 and 3)"
    SKIPPED+=("Fix the dry run: gh run view $run_id --log-failed")
  fi
else
  SKIPPED+=("Actions → Chrome Web Store → Run workflow, tag $LATEST_TAG, dry_run ticked")
fi
pause

finish
say "Next feat/fix merge to main: once CI releases it, the Chrome Web Store workflow"
say "submits the Chrome zip for review. Watch it under Actions → Chrome Web Store."
printf '\n'
