#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Sets up the four GitHub secrets that let CI submit releases to the Chrome Web
# Store (scripts/release/submit-chrome-web-store.sh):
#
#   scripts/setup-chrome-web-store.sh
#
# The non-secret values are also saved to apps/extension/.env.submit (git-ignored),
# which `wxt submit` reads, so re-runs offer them as defaults and you can run
# `cd apps/extension && bunx wxt submit status` later. The private key only goes to
# GitHub.

cd "$(dirname "$0")/.."
export GH_REPO="zhangchi0104/open-browser-translate"
ENV_FILE="apps/extension/.env.submit"
DEVCONSOLE="https://chrome.google.com/webstore/devconsole"

TOTAL_STAGES=9

banner "Chrome Web Store release setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check prerequisites"
ok=true
if ! command -v bun >/dev/null 2>&1; then
  warn "bun is not installed: https://bun.sh"; ok=false
elif [[ ! -x apps/extension/node_modules/.bin/wxt ]]; then
  warn "Dependencies are not installed. Run: bun install"; ok=false
fi
if ! command -v gh >/dev/null 2>&1; then
  warn "The GitHub CLI is not installed: https://cli.github.com"; ok=false
elif ! gh auth status >/dev/null 2>&1; then
  warn "gh is not signed in. Run: gh auth login"; ok=false
else
  permission=$(gh repo view "$GH_REPO" --json viewerPermission -q .viewerPermission 2>/dev/null || true)
  if [[ "$permission" != "ADMIN" ]]; then
    warn "The active gh account can't manage $GH_REPO's secrets (permission: ${permission:-none})."
    note "Switch to the owner: gh auth switch --user zhangchi0104"
    ok=false
  fi
fi
if [[ "$ok" != true ]]; then
  printf '\n'; say "Fix the above, then run this wizard again."; exit 1
fi
say "${GREEN}✓${RESET} bun, dependencies and gh (admin on $GH_REPO) are ready."
printf '\n'
say "The Chrome Web Store API can't create a new item, so the first version must"
say "already be uploaded by hand (docs/chrome-web-store-listing.md, sections 0–5)."
confirm "Does the extension already have an item in the developer dashboard?" || {
  say "Create the item first, then run this wizard again."; exit 1; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Chrome Web Store: publisher ID"
open_url "$DEVCONSOLE"
step "Sign in with the account that owns the extension, and pick its publisher if asked."
step "The address bar now reads $DEVCONSOLE/<publisher-id>/…"
step "Copy the <publisher-id> part (between /devconsole/ and the next /)."
ask CHROME_PUBLISHER_ID "Publisher ID:"
while [[ -z "$CHROME_PUBLISHER_ID" || "$CHROME_PUBLISHER_ID" == */* ]]; do
  warn "Paste only the ID segment, without slashes."
  ask CHROME_PUBLISHER_ID "Publisher ID:"
done
write_env CHROME_PUBLISHER_ID "$CHROME_PUBLISHER_ID"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Chrome Web Store: extension ID"
open_url "$DEVCONSOLE/$CHROME_PUBLISHER_ID"
step "In the Items list, click Open Browser Translate."
step "Copy the 32-letter item ID shown under its name (also in the address bar)."
ask CHROME_EXTENSION_ID "Extension ID:"
while [[ ! "$CHROME_EXTENSION_ID" =~ ^[a-p]{32}$ ]]; do
  warn "An extension ID is 32 letters from a to p."
  ask CHROME_EXTENSION_ID "Extension ID:"
done
write_env CHROME_EXTENSION_ID "$CHROME_EXTENSION_ID"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: enable the Chrome Web Store API"
open_url "https://console.cloud.google.com/apis/library/chromewebstore.googleapis.com"
step "At the top of the page, pick a project, or create one (e.g. open-browser-translate)."
step "Click Enable. If it says Manage / API Enabled, it's already on."
note "No billing account is needed for this API."
pause "Press Enter once the API is enabled."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: service account and JSON key"
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts/create"
step "Same project as the last stage. Name it e.g. chrome-web-store-ci."
step "Click Create and continue. Grant it no roles: click Continue, then Done."
step "Click the new account → Keys tab → Add key → Create new key → JSON → Create."
step "Your browser downloads a .json key file."
note "If key creation is blocked by an organization policy, use a project outside"
note "that organization (a personal Google account has no such policy)."
printf '\n'
KEY_FILE=""
while :; do
  ask KEY_FILE "Path to the downloaded .json file (you can drag it here):"
  KEY_FILE="${KEY_FILE%\"}"; KEY_FILE="${KEY_FILE#\"}"
  KEY_FILE="${KEY_FILE%\'}"; KEY_FILE="${KEY_FILE#\'}"
  # Dragging a file into the terminal adds a trailing space and escapes spaces.
  KEY_FILE="${KEY_FILE%"${KEY_FILE##*[![:space:]]}"}"; KEY_FILE="${KEY_FILE//\\ / }"
  KEY_FILE="${KEY_FILE/#\~/$HOME}"
  [[ -f "$KEY_FILE" ]] || { warn "No file at $KEY_FILE"; continue; }
  CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL=$(KEY_FILE="$KEY_FILE" bun -e \
    'console.log(JSON.parse(require("fs").readFileSync(process.env.KEY_FILE, "utf8")).client_email ?? "")' 2>/dev/null || true)
  CHROME_SERVICE_ACCOUNT_PRIVATE_KEY=$(KEY_FILE="$KEY_FILE" bun -e \
    'console.log(JSON.parse(require("fs").readFileSync(process.env.KEY_FILE, "utf8")).private_key ?? "")' 2>/dev/null || true)
  if [[ -n "$CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL" && "$CHROME_SERVICE_ACCOUNT_PRIVATE_KEY" == "-----BEGIN PRIVATE KEY-----"* ]]; then
    break
  fi
  warn "That isn't a service account key (no client_email / private_key)."
done
say "${GREEN}✓${RESET} Read the key for $CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL"
write_env CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL "$CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL"
write_env CHROME_API_VERSION v2

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Chrome Web Store: link the service account"
open_url "$DEVCONSOLE/$CHROME_PUBLISHER_ID"
step "In the left sidebar, open Account."
step "Find the service account setting and add this email, then save:"
printf '\n      %s%s%s\n\n' "$BOLD" "$CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL" "$RESET"
note "A publisher can have only one service account; replace any old one."
pause "Press Enter once it's saved."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Check that CI will be able to sign in"
say "Asking the Chrome Web Store API for the item's status with these values."
say "This only reads; nothing is uploaded or submitted."
printf '\n'
check_access() {
  ( cd apps/extension && \
    CHROME_API_VERSION=v2 \
    CHROME_EXTENSION_ID="$CHROME_EXTENSION_ID" \
    CHROME_PUBLISHER_ID="$CHROME_PUBLISHER_ID" \
    CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL="$CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL" \
    CHROME_SERVICE_ACCOUNT_PRIVATE_KEY="$CHROME_SERVICE_ACCOUNT_PRIVATE_KEY" \
    bunx wxt submit status )
}
verified=false
while :; do
  if check_access; then verified=true; break; fi
  printf '\n'
  warn "The API rejected these values. Usual causes:"
  note "  401/403: the service account isn't linked yet (stage 6), or it was just"
  note "           linked; wait a minute and retry"
  note "  403:     the API isn't enabled in the key's project (stage 4)"
  note "  404:     the publisher or extension ID is wrong (stages 2-3)"
  confirm "Retry?" || break
done
if [[ "$verified" != true ]]; then
  confirm "Set the GitHub secrets anyway?" || { say "Nothing was sent to GitHub."; exit 1; }
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "GitHub: set the release secrets"
say "These go to $GH_REPO → Settings → Secrets and variables → Actions:"
note "  CHROME_EXTENSION_ID                  $CHROME_EXTENSION_ID"
note "  CHROME_PUBLISHER_ID                  $CHROME_PUBLISHER_ID"
note "  CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL  $CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL"
note "  CHROME_SERVICE_ACCOUNT_PRIVATE_KEY   (hidden, from the JSON key)"
printf '\n'
warn "From the next feat/fix release on main, CI submits every release for review."
if confirm "Set them now (overwrites existing values)?"; then
  set_secret CHROME_EXTENSION_ID "$CHROME_EXTENSION_ID"
  set_secret CHROME_PUBLISHER_ID "$CHROME_PUBLISHER_ID"
  set_secret CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL "$CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL"
  set_secret CHROME_SERVICE_ACCOUNT_PRIVATE_KEY "$CHROME_SERVICE_ACCOUNT_PRIVATE_KEY"
else
  SKIPPED+=("GitHub secrets (re-run this wizard to set them)")
fi
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Delete the local key file"
say "The private key now lives in GitHub. Keeping the JSON file around only adds risk;"
say "if you lose access, create a new key in Google Cloud and re-run this wizard."
printf '\n'
if confirm "Delete $KEY_FILE?"; then
  rm -f -- "$KEY_FILE"
  say "${GREEN}✓${RESET} Deleted."
else
  SKIPPED+=("Delete or safely store $KEY_FILE; never commit it")
fi
pause

finish
say "Next feat/fix merge to main: once CI releases it, the Chrome Web Store workflow"
say "submits the Chrome zip for review. Watch it under Actions → Chrome Web Store."
say "To check now: Run workflow there with the latest tag and dry_run ticked."
printf '\n'
